name: Prisma Twistcli Scan

on:
  push:
    branches:
      - main

jobs:

  image-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t demo-app:${{ github.sha }} .

      - name: Download twistcli
        env:
          CONSOLE: ${{ secrets.PRISMA_CONSOLE }}
          ACCESS_KEY: ${{ secrets.PRISMA_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.PRISMA_SECRET_KEY }}
        run: |
          curl -k \
            -u "$ACCESS_KEY:$SECRET_KEY" \
            "$CONSOLE/api/v1/util/twistcli" \
            -o twistcli

          chmod +x twistcli

      - name: Verify twistcli
        run: |
          ./twistcli --version

      - name: Scan Docker Image
        env:
          CONSOLE: ${{ secrets.PRISMA_CONSOLE }}
          ACCESS_KEY: ${{ secrets.PRISMA_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.PRISMA_SECRET_KEY }}
        run: |
          ./twistcli images scan \
            --address $CONSOLE \
            --user $ACCESS_KEY \
            --password $SECRET_KEY \
            demo-app:${{ github.sha }}
